### ISSUE TITLE
Drift Map Images Not Saved In New Pipeline

### ISSUE THREAD

**Issue by arjunsridhar12345** [AllenNeuralDynamics/aind-ephys-pipeline-kilosort25#6]
The drift map images are currently not saved in the new pipeline. Is this an easy change so they can be saved, or is there a way to access the relevant data to make them?

**Comment by alejoe91** [comment]
They can be viewed from the timeseries link in the visualization_output.json so the PNG are not saved anymore

**Comment by alejoe91** [comment]
@arjunsridhar12345 I'm going to close this
